# Generated by Django 4.2.6 on 2024-04-21 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
